require 'aruba/cucumber'

# Generated by cucumber-sinatra. (2011-01-06 15:16:58 -0600)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/bender/dashboard.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Bender::Dashboard

class Bender::DashboardWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  Bender::DashboardWorld.new
end
